first commit
tenantcloud/ansible-role-create-user pull request #1
Opened 2020-11-11 16:33 UTC by odebretseni

2020-11-12 07:40 UTC, BrunIF requested changes

2020-11-12 07:40 UTC, BrunIF commented on tasks/configure-users.yml
> +  loop: "{{ sudo_users }}"
Створити для кожного користувача окремий файл з його іменем у папці `/etc/sudoers.d/`
Так і правильніше, і буде зручніше видаляти.

2020-11-12 07:40 UTC, BrunIF commented on tasks/configure-users.yml
> +    groups: sudo, ubuntu, adm
для користувача група `{{ item.username }}` створиться автоматично? 
+ я б це робив змінною у vars. Там можна буде перевизначати групи до яких має додати користувача.

2020-11-12 10:56 UTC, odebretseni commented on tasks/configure-users.yml
> +    groups: sudo, ubuntu, adm
для користувача група {{ item.username }} створиться автоматично? - Так

2020-11-13 08:27 UTC, BrunIF approved these changes

2020-11-13 08:36 UTC, vikfedkiv approved these changes

2020-11-13 14:03 UTC, merged